[server]
maxUploadSize = 1000
maxMessageSize = 1000
memory = 8192
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false

[runner]
# Increase memory limit for the Streamlit runner
memory = 8192
# Set number of workers
magicEnabled = true
maxNumberOfWorkers = 4

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"