[server]
maxUploadSize = 1000
maxMessageSize = 1000
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false

[runner]
# Increase memory limit for the Streamlit runner
magicEnabled = true

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
